openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/rightech/api-v1/1.0.0
info:
  version: '1.0.0'
  title: rightech-iot-api
  description: Rightech IOT Web Services
paths:
  /models:
    get:
      description: returns all registered devices
      operationId: GET /models
      # parameters:
      #   - in: query
      #     name: skip
      #     description: number of records to skip
      #     schema:
      #       type: integer
      #       format: int32
      #   - in: query
      #     name: limit
      #     description: max number of records to return
      #     schema:
      #       type: integer
      #       format: int32
      responses:
        '200':
          description: All the devices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Model'
                    
components:
  schemas:
    # include ./schemas/**/*.yaml
